language: php

php:
  - 7.4

sudo: false

services:
  - mysql

mysql:
  database: test
  username: root
  encoding: utf8

before_install:
  - composer self-update --verbose --2
  - composer --version
  - export COMPOSER_MEMORY_LIMIT=-1
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - mysql -e "create database IF NOT EXISTS test;"
  - wget --no-check-certificate https://www.drupal.no/sanitized.db
install:
  - composer install
  - cd ${TRAVIS_BUILD_DIR}/web/themes/drupal_nl && ./build.sh && rm -rf node_modules && cd ${TRAVIS_BUILD_DIR}/web
  - touch sites/default/settings.local.php
  - ./../vendor/drush/drush/drush si minimal --verbose --yes --db-url=mysql://root@127.0.0.1/test
script:
  - cd ${TRAVIS_BUILD_DIR}/web
  - ./../vendor/drush/drush/drush sql-cli < ../sanitized.db
  - ./../vendor/drush/drush/drush cr
  - ./../vendor/drush/drush/drush updb -y
  - ./../vendor/drush/drush/drush cim -y
  - ./../vendor/drush/drush/drush cr
